# Numpy
#### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## Installing and importing Numpy

In [3]:
pip install numpy 
import numpy as np


## NumPy Array

#### An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

### Creating *Array*

In [32]:
a = np.array([1,2,3,4]) #One Dimentional
print(a)
b = np.array([[1,2,3],[4,5,6]]) #Two Dimentional
print(b)
c = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]]) #Three Dimentional
print(c)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


### Various kinds of array

In [27]:
#array filled with 0’s:
zeros = np.zeros((4,5))
print(zeros)
print("--------------------")
#array filled with 1’s:
ones = np.ones((2,3))
print(ones)
print("--------------------")
# an empty array
empty = np.empty(5)
print(empty) # # may vary


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------
[ 1.    3.25  5.5   7.75 10.  ]


In [23]:
#array with a range of elements:
range_array1 = np.arange(10)
print(range_array1)
print("--------------------")
range_array2 = np.arange(5,10, dtype=float)
print(range_array2)
print("--------------------")
range_array3 = np.arange(0,20,2)
print(range_array3)
print("--------------------")


#array with values that are spaced linearly in a specified interval:
specific_array1 = np.linspace(1,10,5)
print(specific_array1)
print("--------------------")
specific_array2 = np.indices((4,3))
print(specific_array2)
print("--------------------")

[0 1 2 3 4 5 6 7 8 9]
--------------------
[5. 6. 7. 8. 9.]
--------------------
[ 0  2  4  6  8 10 12 14 16 18]
--------------------
[ 1.    3.25  5.5   7.75 10.  ]
--------------------
[[[0 0 0]
  [1 1 1]
  [2 2 2]
  [3 3 3]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]
--------------------


## Shape & Size of Array

In [36]:
example1 = np.array([[1,5,7,8],[0,2,8,9]])
example2 = np.array([0,5,9,4,7])
example3 = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])


In [37]:
#number of dimensions of the array

print(example1.ndim)
print("--------")
print(example2.ndim)
print("-------")
print(example3.ndim)
print("-------")


2
--------
1
-------
3
-------


In [38]:
# total number of elements in the array

print(example1.size)
print("--------")
print(example2.size)
print("--------")
print(example3.size)


8
--------
5
--------
18


In [39]:
# the shape of your array
print(example1.shape)
print("--------")
print(example2.shape)
print("--------")
print(example3.shape)


(2, 4)
--------
(5,)
--------
(3, 2, 3)


### Reshaping Array

In [45]:
example1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(example1)
print("--------")
print(example1.reshape(3,4))
print("--------")
print(np.reshape(example1, newshape=(3,4)))
print("--------")
print(np.reshape(example1, newshape=(6,2)))
print("--------")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
--------


### Convert a 1D array into a 2D array

In [73]:
example1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(example1)
print(example1.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [76]:
#use np.newaxis to add a new axis:
result1 = example1[np.newaxis, :]
print(result1)
print("-------")
print(result1.shape)
print("-------")
result2 = example1[: , np.newaxis]
print(result2)
print("-------")
print(result2.shape)
result3 = example1[2:5 , np.newaxis]
print(result3)
print("-------")
print(result3.shape)


[[ 1  2  3  4  5  6  7  8  9 10]]
-------
(1, 10)
-------
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
-------
(10, 1)
[[3]
 [4]
 [5]]
-------
(3, 1)


In [78]:
#use np.expand_dims to add an axis at index position 1 or 2:

result1 = np.expand_dims(example1, axis=0)
print(result1)
print("------")
print(result1.shape)
print("-----")
result2 = np.expand_dims(example1, axis=1)
print(result2)
print("------")
print(result2.shape)

[[ 1  2  3  4  5  6  7  8  9 10]]
------
(1, 10)
-----
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
------
(10, 1)


## Sorting and Concatenate elements

### Sorting

In [51]:
example1 = np.array([10,25,45,11,2,99,45,12,34])
print(example1)
print("--------")
example2 = np.array([[1,5,7,8],[0,2,8,9]])
print(example2)
print("--------")
example3 = np.array([[[0,1,2],[3,4,5],[9,8,7]],[[6,7,8],[9,10,11],[4,6,5]],[[12,13,14],[15,16,17],[1,5,9]]])
print(example3)

[10 25 45 11  2 99 45 12 34]
--------
[[1 5 7 8]
 [0 2 8 9]]
--------
[[[ 0  1  2]
  [ 3  4  5]
  [ 9  8  7]]

 [[ 6  7  8]
  [ 9 10 11]
  [ 4  6  5]]

 [[12 13 14]
  [15 16 17]
  [ 1  5  9]]]


In [60]:
#sort the numbers in ascending order
print(np.sort(example1))
print("--------")
print(np.sort(example3, axis= 2))

[ 2 10 11 12 25 34 45 45 99]
--------
[[[ 0  1  2]
  [ 3  4  5]
  [ 7  8  9]]

 [[ 6  7  8]
  [ 9 10 11]
  [ 4  5  6]]

 [[12 13 14]
  [15 16 17]
  [ 1  5  9]]]


### Concatenate

In [63]:
example1 = np.array([1, 2, 3, 4])
example2 = np.array([5, 6, 7, 8])

In [65]:
np.concatenate((example1,example2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
example3 = np.array([[1, 2], [3, 4]])
example4 = np.array([[5, 6]])

In [69]:
np.concatenate((example3,example4), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Indexing and slicing

In [79]:
example1 = np.array([10,25,45,11,2,99,45,12,34])
print(example1)
print("--------")
example2 = np.array([[1,5,7,8],[0,2,8,9]])
print(example2)
print("--------")
example3 = np.array([[[0,1,2],[3,4,5],[9,8,7]],[[6,7,8],[9,10,11],[4,6,5]],[[12,13,14],[15,16,17],[1,5,9]]])
print(example3)

[10 25 45 11  2 99 45 12 34]
--------
[[1 5 7 8]
 [0 2 8 9]]
--------
[[[ 0  1  2]
  [ 3  4  5]
  [ 9  8  7]]

 [[ 6  7  8]
  [ 9 10 11]
  [ 4  6  5]]

 [[12 13 14]
  [15 16 17]
  [ 1  5  9]]]


In [83]:
#For one dimention
print(example1[4])
print("--------")
print(example1[-4])
print("--------")
print(example1[2:8])
print("--------")
print(example1[-4:])
print("--------")

2
--------
99
--------
[45 11  2 99 45 12]
--------
[99 45 12 34]
--------


In [92]:
#For multiple dimention (Row,Column)
print(example2[1])
print("--------")
print(example2[1,2])
print("--------")
print(example3[1,2])
print("--------")
print(example3[1,2,1])
print("--------")


[0 2 8 9]
--------
8
--------
[4 6 5]
--------
6
--------


### Select elements from array that fulfill certain conditions

In [94]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
#values in the array that are less than 5
print(a[a < 5])


[1 2 3 4]


In [97]:
#numbers that are equal to or greater than 5
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [98]:
#select elements that are divisible by 2:
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [100]:
#select elements that satisfy two conditions using the & and | operators:
print(a[(a > 2) & (a < 11)])

[ 3  4  5  6  7  8  9 10]


In [101]:
#use of the logical operators & and | in order to return boolean values:
print((a > 5) | (a == 5))

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
